# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"\x17\n\x07Request\x12\x0c\n\x04\x62yte\x18\x01 \x01(\x0c\"\x19\n\x08Response\x12\r\n\x05\x65mbed\x18\x01 \x01(\t20\n\x0erequestservice\x12\x1e\n\x05Start\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=15
  _globals['_REQUEST']._serialized_end=38
  _globals['_RESPONSE']._serialized_start=40
  _globals['_RESPONSE']._serialized_end=65
  _globals['_REQUESTSERVICE']._serialized_start=67
  _globals['_REQUESTSERVICE']._serialized_end=115
# @@protoc_insertion_point(module_scope)
